### ISSUE TITLE
Extra Requirement in Practical Guide

### ISSUE THREAD

**Issue by johnsona12** [Allegheny-Computer-Science-103-S2018/cs103-S2018-sheets#1]
Hi Professor! The practical requirements say we need to write a reflection, but we do not need to write a reflection for this assignment.
[cs103S2018_practical01.pdf](https://github.com/Allegheny-Computer-Science-103-S2018/cs103-S2018-sheets/files/1668104/cs103S2018_practical01.pdf)

**Comment by gkapfham** [comment]
Hello @johnsona12! Thanks for pointing out that the practical assignment incorrectly required the writing of a reflection document. I have fixed this mistake so that this incorrect requirement is no longer there. You can find the current version of the assignment by visiting the [Releases](https://github.com/Allegheny-Computer-Science-103-S2018/cs103-S2018-sheets/releases) page for this repository.

Overall, I think that this issue is now resolved and I will close it. If you think that there is something that I have overlooked concerning this issue, please comment in this thread. Thanks again!
